### PR TITLE
feat: Add Image Categorization Section

### PR DESCRIPTION
**Pull request by nicknamenamenick**
Would love feedback on this.  I am suggesting we should start to breakdown and categorize these images based on their purpose.  

I know there might still be confusion on the naming to follow Fedora's current naming scheme, so that might be something I will consider down the road too.  I would like to have users to be able to pick an image and know exactly what all of their choices are what each image means eventually.

For now, I offer categorization.  Please let me know what should be improved or if this whole idea should be scrapped and/or moved elsewhere.

### CODE REVIEW

**Comment by castrojo** [comment]
I'm not sure about the use of "flagship" as a term, let's see what others thing. @ublue-os/approver @ublue-os/member

**Comment by bobslept** [comment]
I would just use something like `Opionated images by teammembers`, Bazzite being focused on gaming, Bluefin being focused on combining fedora with ubuntu, beyond being focused on showing (maybe) the future of gnome. For me these variants are to show what this project can do, some sort of examples even. What it is capable of. Even when they are full blown everyday usable images with major work being done on them. If you get my idea, not want to downplay anything here :smiley:

**Comment by nicknamenamenick** [comment]
I do like "Featured Images" or something else.  Yeah maybe flagship isn't a good term especially since right now Bluefin, Bazzite, and Beyond are not as popular as the Silverblue, Kinoite, etc. images.

**Comment by xynydev** [comment]
+1 for featured images, no reason a popular and featureful image made by a non-ublue org member couldn't be featured

**Review by castrojo — APPROVED** [review]

**Comment by castrojo** [comment]
We ready with this one?

**Pull request merged**
