### PR TITLE
Feat: Add Showcase to Homepage + Slight redesign

### PR DESCRIPTION
**Pull request by nicknamenamenick**
...Also made some most likely controversial changes.  This all started because the table showing the different features like (Images, Experimental Applications, etc.) were 3 on top and then "Community" at the bottom left.  I initially attempted to move it towards the middle, but was unsure if that was possible.  

I'm not even sure if what I did would even work properly if/when these changes land.

I also added bullet points for the different DE/WM for each of the images, the hardware specific images, and the 'special' images.

Then I added a showcase of Universal Blue's Fedora Silverblue image, the XFCE/Vauxite image, Bazzite, and Bluefin.

I fully understand if these changes do not land.  If anyone wants to give me any feedback at all that would be appreciative.

### CODE REVIEW

**Comment by castrojo** [comment]
Do you have a screenshot of what it looks like handy?

**Comment by nicknamenamenick** [comment]
> Do you have a screenshot of what it looks like handy?

https://hackmd.io/cwtB8_BoQvOFxTo9mk95gw

Created this team document right now, but none of the material icons show up, nor does the tables.  This probably does not help and I don't have anyway to view if this will look correct.

I got the material icons from here: https://pictogrammers.com/library/mdi/

**Comment by xynydev** [comment]
> Created this team document right now, but none of the material icons show up, nor does the tables. This probably does not help and I don't have anyway to view if this will look correct.

That's because the markup language the page is written in is not markdown, but a special, shittier (ok, extra features, but the list parsing is infuriating) version, used by MkDocs.

**Comment by xynydev** [comment]
I'm now kind of interested in workin on an upgraded version, too. Since the project's homepage isn't probably changing to a non-docs page anytime soon, might as well add some glitter.

**Pull request closed without merging**
