### PR TITLE
updated to list all non-OS images

### LINKED ISSUE #530: remove the "rpm-ostree" commands from Distrobox images
I see the Distrobox images are not to be used as system, but as Distrobox containers. 

I guess the creation command is somewhat automatic, but it should be changed to 

```
distrobox create NAME -i URL
```

### PR DESCRIPTION
**Pull request by firefoxlover**
fixes #530

### CODE REVIEW

**Review by castrojo — APPROVED** [review]
Thank you so much!

**Comment by firefoxlover** [comment]
always there to help, great project!

Btw, is there a Matrix channel or something not Discord?

**Comment by castrojo** [comment]
No but we try to be as async we can: https://universal-blue.org/CONTRIBUTING/?#why-we-insist-on-using-github

And we always do important things in github, major decisions, we have a proposal process, etc. to try to help keep that habit alive.

**Comment by castrojo** [comment]
However if you filed an issue in ublue-os/main and ask if anyone is interested in maintaining it and there's enough trusted people who want to do it and hang out in it, sure.

I'm a strong -1 on a bridge though because the UX is just awful, let's just accept that it's a different medium and helps reinforce the github-first culture.

**Pull request merged**
